---
- name: show ip address from facts
  hosts: all
  gather_facts: false

  tasks:
    - name: show ip address
      debug: 
        msg: "The ip address is {{ ansible_facts['default_ipv4']['address'] }}"
...
